server:
  port: 8080
  servlet:
    context-path: /api/v1/fincontrol

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/fincontrol
    username: fincontrol
    password: fincontrol
    driverClassName: org.postgresql.Driver

fincontrol:
  security:
    jwtSecret: 9a02115a835ee03d5fb83cd8a468ea33e4090aaaec87f53c9fa54512bbef4db8dc656c82a315fa0c785c08b0134716b81ddcd0153d2a7556f2e154912cf5675f
    jwtExpirationInMs: 604800000
