server:
  port: 8080
  servlet:
    context-path: /api/v1/fincontrol

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/fincontrol
    username: fincontrol
    password: fincontrol
    driverClassName: org.postgresql.Driver
